version: '3.8'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
             - ./app:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_SQL_ROOT_PASSWORD: 'test' 
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'test'
            MYSQL_DATABASE: 'joke_db'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - mysql
        environment:
            PMA_HOST: 'mysql' 
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'test'
            MYSQL_DATABASE: 'joke_db'
volumes:
    mysqldata: {}
